from __future__ import annotations

from typing import Any, Protocol

from .batch import Batch
from .context import ExperimentContext
from .result import StepResult
from .state import RunState


class Algorithm(Protocol):
    """Task-neutral algorithm lifecycle.

    A concrete algorithm decides whether a cycle is an epoch, EM iteration, active
    learning round, diffusion stage, or something else.
    """

    def setup(self, context: ExperimentContext) -> None: ...
    def on_run_start(self, state: RunState) -> None: ...
    def on_cycle_start(self, state: RunState) -> None: ...
    def step(self, batch: Batch, state: RunState) -> StepResult: ...
    def on_cycle_end(self, state: RunState) -> StepResult: ...
    def on_run_end(self, state: RunState) -> StepResult: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state: dict[str, Any]) -> None: ...
    def close(self) -> None: ...

